// Lagos Zone Mapping for Delivery Fee Calculation
// Zone 1: Lagos Island (Premium Zone)
// Zone 2: Lagos Mainland Central
// Zone 3: Greater Lagos Area
// Zone 4: Lagos Outskirts
// Zone 5: Neighboring Areas (Extended Delivery)

export const lagosZoneMapping = {
  // ZONE 1: Lagos Island (Premium Zone) - ₦1,000
  "Zone 1": {
    zoneName: "Lagos Island (Premium Zone)",
    deliveryFee: 1000,
    areas: [
      "Victoria Island",
      "Ikoyi",
      "Lekki Phase 1",
      "Banana Island",
      "Eko Atlantic",
      "Lagos Island",
      "Marina",
      "Oniru",
      "Ozumba Mbadiwe",
      "Ademola Adetokunbo",
      "Kofo Abayomi",
      "Idowu Taylor",
      "Adeola Odeku",
      "Akin Adesola",
      "Civic Centre",
      "Bar Beach",
      "Kuramo Beach",
      "Tiamiyu Savage",
      "Bishop Oluwole",
    ],
  },

  // ZONE 2: Lagos Mainland Central - ₦1,500
  "Zone 2": {
    zoneName: "Lagos Mainland Central",
    deliveryFee: 1500,
    areas: [
      "Surulere",
      "Yaba",
      "Ikeja",
      "Maryland",
      "Ilupeju",
      "Anthony Village",
      "Opebi",
      "Allen Avenue",
      "Ogba",
      "Alausa",
      "Oregun",
      "Ojota",
      "Ogudu",
      "Gbagada",
      "Oworonshoki",
      "Ikeja GRA",
      "Akoka",
      "Jibowu",
      "Onipanu",
      "Fadeyi",
      "Mushin",
      "Palmgrove",
      "Shomolu",
      "Bariga",
      "Ikorodu Road",
      "Obanikoro",
      "Pedro",
      "Mende",
      "Shangisha",
      "Magodo Phase 1",
      "Magodo Phase 2",
      "Isheri North",
      "Omole Phase 1",
      "Omole Phase 2",
    ],
  },

  // ZONE 3: Greater Lagos Area - ₦2,000
  "Zone 3": {
    zoneName: "Greater Lagos Area",
    deliveryFee: 2000,
    areas: [
      "Lekki Phase 2",
      "Lekki Gardens",
      "Chevron",
      "VGC",
      "Ajah",
      "Sangotedo",
      "Awoyaya",
      "Ikota",
      "Agungi",
      "Idado",
      "Ikate Elegushi",
      "Chisco",
      "Igbo Efon",
      "Jakande",
      "Ilasan",
      "Osapa London",
      "Amuwo Odofin",
      "Festac Town",
      "Satellite Town",
      "Ojo",
      "Alaba International",
      "Trade Fair",
      "Agege",
      "Oko Oba",
      "Abule Egba",
      "Ifako-Ijaiye",
      "Fagba",
      "Iju",
      "Ojodu",
      "Ojodu Berger",
      "Isheri",
      "Magboro",
      "Arepo",
      "Berger",
      "Mile 2",
      "Ago Palace Way",
      "Okota",
      "Isolo",
      "Ejigbo",
      "Egbe",
      "Ikotun",
      "Iyana Ipaja",
      "Egbeda",
      "Idimu",
      "Igando",
      "Iba",
      "LASU",
    ],
  },

  // ZONE 4: Lagos Outskirts - ₦3,000
  "Zone 4": {
    zoneName: "Lagos Outskirts",
    deliveryFee: 3000,
    areas: [
      "Ikorodu",
      "Epe",
      "Badagry",
      "Ibeju-Lekki",
      "Akodo",
      "Eleko",
      "Lakowe",
      "Bogije",
      "Shapati",
      "Oke-Odo",
      "Ayobo",
      "Ipaja",
      "Meiran",
      "Okokomaiko",
      "Iyana Iba",
      "Igbogbo",
      "Ijede",
      "Imota",
      "Agbowa",
      "Owode",
      "Mokoloki",
      "Ogijo",
      "Agbara",
      "Oto-Awori",
      "Mowe",
      "Ibafo",
      "Ajah Extension",
      "Abraham Adesanya",
      "Badore",
      "Ogombo",
      "Ibeju",
      "Abijo GRA",
      "Awoyaya Extension",
      "LBS",
      "Okunraiye",
      "Free Trade Zone",
      "Aiyeteju",
      "Akodo",
      "Folu",
      "Dangote Refinery Area",
    ],
  },

  // ZONE 5: Neighboring Areas (Extended Delivery) - ₦4,000
  "Zone 5": {
    zoneName: "Neighboring Areas (Extended Delivery)",
    deliveryFee: 4000,
    areas: [
      "Sango Ota",
      "Mowe Ofada",
      "Shimawa",
      "Redeem",
      "Pakuro",
      "Lotto",
      "Magboro Extension",
      "Ibafo Extension",
      "Abeokuta Express",
      "Atan",
      "Iju-Ota",
      "Agbado",
      "Lambe",
      "Akute",
      "Matogun",
      "Iju-Ishaga",
      "Alagbole",
      "Ajuwon",
      "Tabon-Tabon",
      "Ijoko",
      "Itoki",
      "Ifo",
      "Aseese",
      "MFM",
      "Ijeshatedo-Ota",
      "Abeokuta Road",
      "Papalanto",
      "Ogere",
      "Sagamu Interchange",
    ],
  },
};
